---
name: groovy-language-server
description: A language server for Groovy.
homepage: https://github.com/GroovyLanguageServer/groovy-language-server
licenses:
  - Apache-2.0
languages:
  - Groovy
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/GroovyLanguageServer/groovy-language-server@8b5fbc3449cb6b4b5c6e1e6b793e3abb51b88ecf
  build:
    run: ./gradlew --no-daemon build

bin:
  groovy-language-server: java-jar:build/libs/groovy-language-server-all.jar
