---
name: drools-lsp
description: An implementation of a language server for the Drools Rule Language.
homepage: https://github.com/kiegroup/drools-lsp
licenses:
  - Apache-2.0
languages:
  - Drools
categories:
  - LSP

source:
  # renovate:datasource=git-refs
  id: pkg:github/kiegroup/drools-lsp@7a025b1b99b18cfb33576cd4076d0a1b02ae009d
  asset:
    file: drools-lsp-server-jar-with-dependencies.jar
